### ISSUE TITLE
Known compiling .config?

### ISSUE THREAD

**Issue by schierlm** [jeremie-koenig/busybox-osports#1]
Is there a .config that is known to actually build on GNU/Hurd? I tried, and needed to tweak a few places to get it compile, and now finally it compiles, but the linker spews a few dozen undefined symbols at me...

So I'd like to start with a known good .config that does not include anything that breaks the build..., and then probably add other stuff I need (or just use normal binaries instead if it is too hard).

My .config: http://ix.io/2rlr
My output (shell_common.c and some other files are already patched slightly to make it compile): http://ix.io/2rlq

**Comment by schierlm** [comment]
Never mind, got it building. I missed the C file names in the ld output (which roughly correspond to the applets). I needed to `#define major` and `minor` (just dummy) but then it worked.

By the way, do you know if there is any more recent version of busybox tested/ported to Hurd? The latest vanilla version fails a lot with undefined PATH_MAX even in code shared by applets...

**Comment by jeremie-koenig** [comment]
Thank you for the report! I've been out of the loop for a while, so your best bet may be to ask on one of the GNU/Hurd mailing lists.
